#!/usr/bin/env python3
"""
Release script for LandingZone mod.
Copies essential mod files from LZ-DEV to LandingZone (clean release folder).
"""

import os
import shutil
from pathlib import Path

# Paths
DEV_DIR = Path(__file__).parent.parent  # LZ-DEV
RELEASE_DIR = DEV_DIR.parent / "LandingZone"

# Folders to copy
FOLDERS_TO_COPY = ["About", "Assemblies", "Defs", "Languages", "Patches"]

def clean_release_folder():
    """Remove existing release folder contents."""
    if RELEASE_DIR.exists():
        print(f"Cleaning {RELEASE_DIR}...")
        shutil.rmtree(RELEASE_DIR)
    RELEASE_DIR.mkdir(exist_ok=True)

def copy_folder(folder_name):
    """Copy a folder from dev to release."""
    source = DEV_DIR / folder_name
    dest = RELEASE_DIR / folder_name

    if not source.exists():
        print(f"  ⚠ {folder_name}/ not found, skipping")
        return

    print(f"  ✓ Copying {folder_name}/")
    shutil.copytree(source, dest)

def main():
    print("=" * 50)
    print("LandingZone Release Build")
    print("=" * 50)
    print(f"Dev:     {DEV_DIR}")
    print(f"Release: {RELEASE_DIR}")
    print()

    # Clean release folder
    clean_release_folder()

    # Copy essential folders
    print("Copying mod files...")
    for folder in FOLDERS_TO_COPY:
        copy_folder(folder)

    # Remove .gitkeep files if they exist
    for gitkeep in RELEASE_DIR.rglob(".gitkeep"):
        gitkeep.unlink()
        print(f"  ✓ Removed {gitkeep.relative_to(RELEASE_DIR)}")

    # Remove PublishedFileId.txt if it exists (will be generated by Steam)
    published_id = RELEASE_DIR / "About" / "PublishedFileId.txt"
    if published_id.exists():
        published_id.unlink()
        print(f"  ✓ Removed About/PublishedFileId.txt")

    print()
    print("=" * 50)
    print("Release build complete!")
    print("=" * 50)

    # Show release folder size
    total_size = sum(f.stat().st_size for f in RELEASE_DIR.rglob('*') if f.is_file())
    print(f"Release size: {total_size / 1024:.1f} KB")
    print(f"Files: {sum(1 for _ in RELEASE_DIR.rglob('*') if _.is_file())}")

if __name__ == "__main__":
    main()
